apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: iqss/dataverse-k8s
    context: .
    docker:
      dockerfile: docker/dataverse-k8s/glassfish-dev/Dockerfile
  - image: iqss/solr-k8s
    context: docker/solr-k8s
  local: {}
deploy:
  kustomize: {}
profiles:
  - name: payara
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: docker/dataverse-k8s/payara-dev/Dockerfile
    deploy:
      kustomize:
        path: k8s/experiments/payara
